openapi: 3.0.0
info:
  title: API de Météo Planétaire
  version: 1.0.0
  description: Interface pour obtenir les conditions météorologiques sur différentes planètes

paths:
  /planets/{planetName}/weather:
    get:
      summary: Obtenir les conditions météorologiques sur une planète
      parameters:
        - name: planetName
          in: path
          required: true
          schema:
            type: string
            example: "mars"
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -90
            maximum: 90
            example: 45.5
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -180
            maximum: 180
            example: 23.2
      responses:
        '200':
          description: Conditions météorologiques récupérées avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherConditions'
        '404':
          description: Planète non trouvée
        '400':
          description: Coordonnées invalides

components:
  schemas:
    WeatherConditions:
      type: object
      required:
        - planetName
        - coordinates
        - temperature
        - timestamp
      properties:
        planetName:
          type: string
          example: "mars"
        coordinates:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
        temperature:
          type: object
          properties:
            value:
              type: number
              format: float
            unit:
              type: string
              enum: [CELSIUS, KELVIN, FAHRENHEIT]
              default: KELVIN
        pressure:
          type: object
          properties:
            value:
              type: number
              format: float
            unit:
              type: string
              enum: [PA, HPA, BAR, ATM]
        windSpeed:
          type: object
          properties:
            value:
              type: number
              format: float
            unit:
              type: string
              enum: [KMH, MS, MPH]
        atmosphere:
          type: object
          properties:
            composition:
              type: array
              items:
                type: object
                properties:
                  element:
                    type: string
                  percentage:
                    type: number
                    format: float
            density:
              type: number
              format: float
        timestamp:
          type: string
          format: date-time