services:
  devcontainer:
    image: node:22
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "edge"
      KC_HTTPS_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HTTP_RELATIVE_PATH: "/auth"
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_URL: "https://${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      KC_HOSTNAME_ADMIN_URL: "https://${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: [
      "start",
      "--import-realm",
      "--proxy=edge"
    ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    volumes:
      - ../backend/space-suit-back/src/main/resources:/opt/keycloak/data/import
    network_mode: service:devcontainer

  mockoon:
    image: mockoon/cli:9
    entrypoint: [ "mockoon-cli", "start", "--disable-log-to-file", "-d", "/data", "-p", "3000" ]
    volumes:
      - ../../front/mocks/backend-mocks.json:/data
    network_mode: service:devcontainer
